"""create runs table

Revision ID: 3f7d9083d2ce
Revises: 
Create Date: 2026-09-06 12:53:28.583774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7d9083d2ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_activity_id', sa.String(length=255), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('elevation_gain_meters', sa.Integer(), nullable=True),
    sa.Column('average_heart_rate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_heart_rate BETWEEN 30 AND 250', name='ck_runs_average_heart_rate_range'),
    sa.CheckConstraint('distance_meters > 0', name='ck_runs_distance_meters_positive'),
    sa.CheckConstraint('duration_seconds > 0', name='ck_runs_duration_seconds_positive'),
    sa.CheckConstraint('elevation_gain_meters >= 0', name='ck_runs_elevation_gain_meters_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_activity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    # ### end Alembic commands ###
